name: 福井県のデータをGitHubへPush

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Gitを設定
        run: |
          git config --global user.name github-actions
          git config --global user.email actions@github.com

      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Dockerイメージをビルド
        run: docker-compose build fetch_fukui_data

      - name: data/*.jsonを作成
        run: docker-compose run fetch_fukui_data

      - name: ブランチを作成
        id: branch
        env:
          TZ: JST-9
        run: |
          BRANCH_NAME="update_fukui_data/$(date "+%Y%m%d_%Hh%Mm%Ss")"
          git checkout -b $BRANCH_NAME
          echo "##[set-output name=name]$BRANCH_NAME"

      - name: コミット
        run: |
          git add .
          git commit -m "[Auto] データを更新"

      - name: プッシュ
        run: git push -u origin ${{ steps.branch.outputs.name }}

      - name: Pull request を作成
        uses: actions/github-script@0.9.0
        with:
          script: |
            github.pulls.create({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              title: '[Auto]データ更新 ${{ steps.branch.outputs.name }}',
              head: '${{ steps.branch.outputs.name }}',
              base: context.payload.repository.default_branch,
            })
